# Generated by Django 4.2.6 on 2024-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='thesis',
            table='thesis',
        ),
    ]
