# Generated by Django 4.2.6 on 2024-02-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0002_alter_thesis_id_alter_thesis_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='advisors',
            field=models.ManyToManyField(related_name='advisors_theses', to='ThesisApp.lecture'),
        ),
    ]
