# Generated by Django 4.2.6 on 2024-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0003_alter_thesis_advisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='thesis',
            table=None,
        ),
    ]
