# Generated by Django 4.2.6 on 2024-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0004_alter_thesis_id_alter_thesis_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
