# Generated by Django 4.2.6 on 2024-02-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0005_thesis_is_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='scoring_rubric',
        ),
        migrations.AddField(
            model_name='score',
            name='attitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='presentation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('members', models.ManyToManyField(related_name='council_members', to='ThesisApp.councilmember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
