# Generated by Django 4.2.6 on 2024-02-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0006_remove_score_scoring_rubric_score_attitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmember',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_council', to='ThesisApp.council'),
        ),
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
