# Generated by Django 4.2.6 on 2024-02-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0007_councilmember_council_alter_score_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='thesis_defense_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ThesisApp.thesisdefensecommittee'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_council', to='ThesisApp.council'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_theses', to='ThesisApp.student'),
        ),
    ]
