# Generated by Django 4.2.6 on 2024-02-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0008_council_thesis_defense_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='is_close',
        ),
    ]
