# Generated by Django 4.2.6 on 2024-02-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThesisApp', '0009_remove_thesis_is_close'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='council',
            name='thesis_defense_committee',
        ),
        migrations.RemoveField(
            model_name='councilmember',
            name='thesis_defense_committee',
        ),
        migrations.DeleteModel(
            name='ThesisDefenseCommittee',
        ),
    ]
